pull_request_rules:
  - name: Automatic merge when the pull request has been approved.
    conditions:
      - base=main
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: squash

  - name: Automatic merge when the pull request is made by BotiCordBot.
    conditions:
      - base=main
      - author=everydayrains #BotiCordBot soon
    actions:
      merge:
        method: squash