files:
  - source: /src/docs/**/ru/**/*
    translation: /docs/%two_letters_code%/**/%original_file_name%
  - source: /src/website/website.json
    translation: /website/%two_letters_code%.json

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true