#
# Your Crowdin credentials
#
project_id: "591477"
api_token: CROWDIN_PERSONAL_TOKEN 


#
# Choose file structure in Crowdin
# e.g. true or false
#
languages_mapping: &languages_mapping
preserve_hierarchy: true

#
# Files configuration
#
files:
  - source: /src/**/*
    translation: /%locale_with_underscore%/**/%original_file_name%
