#
# Your Crowdin credentials
#
project_id: "591477"
api_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjUwNzM0YjMwNmJlMTgwZGVlYjQxZTBiYmIxZWRmMmIzNWM4NTVkYjg5MDRhNTExMjkzMDMxZWE5ZTJhYzgyOTVjMjNjYzlmODc3ODhlNzBjIiwiaWF0IjoxNjg1NzgxNTQ1LjA1MTk5MywibmJmIjoxNjg1NzgxNTQ1LjA1MTk5NywiZXhwIjoxNzE3MzE3NTQ0Ljk3MDMxMiwic3ViIjoiMTU4NTA5MTciLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.qDHn7i_Vck6olZlRzahCodt7-2COX8baw0QjE6Bj0Ox6Xu0Ndv0vII_DOpjC2f2Mlv9YQQHeTxxg2089gP0orEtXG1VDoO61-A2zyKxdeWCHsy_fhMXI-QIgJz7yydFLhGSPN7t6KN_hFmG4R6AE7-1emDJLtNAuR-9bR5ArOVkl98HL1DdGsPgx_i1uG_2ku0Mx_ZGCw52ZyVf_YSqPqysYCOyfZEiJJGKgEcLkkQX9ES6HWkZbLUaoeqWT5oQy8yOIEEsTFxMW42pY5jrWGiDMkYQJYJ2vpJfPduH9I7R20iZ0y-BUpreZ-45AeZLhYZYBdnbMcG4pgLPd1-gd8Ok8wHsZvBE5v-qjRohHqCXCzKWFp0tEGgbyqiQSoaboUsBF6fvsetOC7QNkni8WY1a-C3M1S-Bl0Xg2kIanOe5V2BbDidE6tUcHYmTgmcc6D1XBGUQhRf58npje11LJ9iiDU5UR7W4ySxzROtpdVAaUVD2aOBvui9b8zRBP2JZDNQX0U0lSPjpr_lMgsSc0YPNMC5d9xIrJb__P4uuJ6RP36MpaV25j-lrsBJ2AUkkFko8t01qGd161JJNc3rALxul6yjfPqPROjPo1AEbt2eIOBAaNwBVODhyc3claW5B5Lc7F2ndo6CjSmYIyZgq4hbwCY2xFtyBBMSTwgzw6ZkM"


#
# Choose file structure in Crowdin
# e.g. true or false
#
languages_mapping: &languages_mapping

#
# Files configuration
#
files:
  - source: /src/docs/**/*
    translation: /%locale_with_underscore%/docs/**/%original_file_name%
