files:
  - source: /src/docs/ru/*
    translation: /docs/%two_letters_code%/%original_file_name%
  - source: /src/docs/ru/api/*
    translation: /docs/%two_letters_code%/api/%original_file_name%
  - source: /src/docs/ru/sdk/*
    translation: /docs/%two_letters_code%/sdk/%original_file_name%
  - source: /src/website/lang.json
    translation: /website/%two_letters_code%.json

project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN