name: Sync locales

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * * *'


jobs:
  synccrowdin:
    name: Sync repo from Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: crowdin/github-action@v1

        with:
          download_translations: true
          localization_branch_name: crowdin-stage
          skip_untranslated_strings: true
          skip_untranslated_files: true
          export_only_approved: true
          commit_message: 'New Crowdin translations'

          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_labels: 'enhancement'
          pull_request_base_branch_name: 'main'

        env:
          GITHUB_TOKEN: ${{ secrets.BoticordAC_TOKEN }}
          GITHUB_ACTOR: BoticordAC
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
